import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div>
      <Image
            className={styles.borderCircle}
            src="/images/dimas.jpg"
            alt="Next.js Logo"
            width={200}
            height={200}
            priority
          />
        </div>
        <div>
      <h1 className='text-center font-mono'>
        Rahul Chand
      </h1>
      </div>
      </div>
        
        <h1 className='text-red-600'>
          Link to <a className='underline' href="/blogs/first-post"> projects </a> 
        </h1>

        

        
      </main>
    </>
  )
}
